const firstArticle = {
  title: "Don't know about the show yet?",
  image: '/rickandmorty-1.jpeg',
  body: "Rick and Morty is an American adult animated science-fiction sitcom created by Justin Roiland and Dan Harmon for Cartoon Network's nighttime programming block Adult Swim. It is distributed internationally by Warner Bros. Domestic Television. The series follows the misadventures of cynical mad scientist Rick Sanchez and his good-hearted but fretful grandson Morty Smith, who split their time between domestic life and interdimensional adventures that take place across an infinite number of realities, often travelling to other planets and dimensions through portals and on Rick's flying saucer. The general concept of Rick and Morty relies on two conflicting scenarios: domestic family drama, and an alcoholic grandfather dragging his grandson into hijinks."
}

const secondArticle = {
  title: 'Premise and main characters',
  image: '/rickandmorty-2.jpeg',
  body: "The show revolves around the adventures of the members of the Smith household, which consists of parents Jerry and Beth, their children Summer and Morty, and Beth's father, Rick Sanchez, who lives with them as a guest. According to Justin Roiland, the family lives outside of Seattle, Washington. The adventures of Rick and Morty, however, take place across an infinite number of realities, with the characters travelling to other planets and dimensions through portals and Rick's flying saucer. Rick is an eccentric and alcoholic mad scientist, who eschews many ordinary conventions such as school, marriage, love, and family. He frequently goes on adventures with his 14-year-old grandson, Morty, a kind-hearted but easily distressed boy, whose naïve but grounded moral compass plays counterpoint to Rick's Machiavellian ego. Morty's 17-year-old sister, Summer, is a more conventional teenager who worries about improving her status among her peers and sometimes follows Rick and Morty on their adventures. The kids' mother, Beth, is a generally level-headed person and assertive force in the household, though self-conscious about her professional role as a horse surgeon. She is dissatisfied with her marriage to Jerry, a simple-minded and insecure person, who disapproves of Rick's influence over his family.Different versions of the characters inhabit other dimensions throughout the show's multiverse and their personal characteristics can vary from one reality to another. The show's original Rick identifies himself as 'Rick Sanchez of Earth Dimension C-137', in reference to his original universe, but this does not apply to any other member of the Smith household. For instance, in the first-season episode 'Rick Potion #9', after turning the entire world population into monsters, Rick and Morty move to a different dimension, leaving the original Summer, Beth and Jerry behind. Rick and Morty themselves also hail from different dimensions; the season 5 finale 'Rickmurai Jack' shows that the original Rick's original family was murdered by an alternate version of himself, with the season 6 premiere 'Solaricks' revealing that this alternate Rick is Morty's biological grandfather instead of the one the show focuses on."
}

export { firstArticle, secondArticle }
